add_executable(bot_transaction_tests tests/bot_transaction_tests.cpp client/gframe/undo/bot_controller.cpp client/gframe/undo/protocol.cpp tests/core_test_globals.cpp)
target_compile_features(bot_transaction_tests PRIVATE cxx_std_17)
target_include_directories(bot_transaction_tests PRIVATE tests client/gframe)
target_link_libraries(bot_transaction_tests PRIVATE undo_resources advapi32 shell32)
target_link_options(bot_transaction_tests PRIVATE -static -Wl,--gc-sections)
set(UNDO_BOT_TEST_EXE "" CACHE FILEPATH "Built adapted WindBot executable for W2 integration")
set(UNDO_BOT_TEST_RUNTIME "" CACHE PATH "Read-only installed WindBot data for W2 integration")
if(UNDO_BOT_TEST_EXE AND UNDO_BOT_TEST_RUNTIME)
  add_test(NAME bot_transaction_tests COMMAND bot_transaction_tests "${UNDO_BOT_TEST_EXE}" "${UNDO_BOT_TEST_RUNTIME}")
  set_tests_properties(bot_transaction_tests PROPERTIES TIMEOUT 180)
endif()
