add_undo_test(core_lookup_tests tests/core_lookup_tests.cpp)
target_sources(core_lookup_tests PRIVATE tests/core_test_globals.cpp)
target_link_libraries(core_lookup_tests PRIVATE undo_driver)
target_link_options(core_lookup_tests PRIVATE -Wl,--gc-sections)
set_tests_properties(core_lookup_tests PROPERTIES TIMEOUT 60)
