execute_process(COMMAND powershell.exe -NoProfile -ExecutionPolicy Bypass
  -File "${CMAKE_CURRENT_SOURCE_DIR}/tools/Apply-LuaUndoPatch.ps1"
  RESULT_VARIABLE undo_lua_patch_result)
if(NOT undo_lua_patch_result EQUAL 0)
  message(FATAL_ERROR "Deterministic Lua source patch verification failed")
endif()
# C2: fixed-source real engine, Lua compiled as C++ (same ABI as the client).
file(GLOB undo_lua_sources CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/client/lua/src/*.c")
list(FILTER undo_lua_sources EXCLUDE REGEX "/lua(c)?\\.c$")
set_source_files_properties(${undo_lua_sources} PROPERTIES LANGUAGE CXX)
add_library(undo_lua STATIC ${undo_lua_sources})
target_include_directories(undo_lua PUBLIC client/lua/src)
target_compile_features(undo_lua PRIVATE cxx_std_17)
file(GLOB undo_core_sources CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/client/ocgcore/*.cpp")
add_library(undo_ocgcore STATIC ${undo_core_sources})
target_include_directories(undo_ocgcore PUBLIC client/ocgcore)
target_compile_features(undo_ocgcore PRIVATE cxx_std_17)
target_link_libraries(undo_ocgcore PUBLIC undo_lua)
add_library(undo_resources STATIC client/gframe/undo/resource_view.cpp client/gframe/data_manager.cpp client/gframe/file_system.cpp)
target_include_directories(undo_resources PUBLIC client/gframe client/irrlicht/include client/sqlite3)
target_compile_features(undo_resources PUBLIC cxx_std_17)
target_compile_options(undo_resources PRIVATE -ffunction-sections -fdata-sections)
set(undo_libdir "${CMAKE_CURRENT_SOURCE_DIR}/client/bin/release")
target_link_libraries(undo_resources PUBLIC "${undo_libdir}/irrlicht.lib" "${undo_libdir}/sqlite.lib" "${undo_libdir}/zlib.lib" "${undo_libdir}/lzma.lib" "${undo_libdir}/png.lib" "${undo_libdir}/jpeg.lib" "${undo_libdir}/freetype.lib" bcrypt winmm shell32 opengl32 gdi32 imm32)
add_library(undo_driver STATIC client/gframe/undo/core_driver.cpp)
target_compile_features(undo_driver PUBLIC cxx_std_17)
target_link_libraries(undo_driver PUBLIC undo_resources undo_ocgcore)
add_undo_test(resource_view_tests tests/resource_view_tests.cpp)
target_sources(resource_view_tests PRIVATE tests/core_test_globals.cpp)
target_link_libraries(resource_view_tests PRIVATE undo_resources)
target_link_options(resource_view_tests PRIVATE -Wl,--gc-sections)
target_compile_definitions(resource_view_tests PRIVATE UNDO_RESOURCE_FIXTURE="${CMAKE_CURRENT_SOURCE_DIR}/tests/results/resource-root")
add_undo_test(core_rng_tests tests/core_rng_tests.cpp)
target_compile_definitions(core_rng_tests PRIVATE UNDO_RNG_API)
target_link_libraries(core_rng_tests PRIVATE undo_ocgcore)
add_undo_test(core_driver_tests tests/core_driver_tests.cpp)
target_sources(core_driver_tests PRIVATE tests/core_test_globals.cpp)
target_compile_definitions(core_driver_tests PRIVATE UNDO_CORE_FIXTURE="${CMAKE_CURRENT_SOURCE_DIR}/tests/results/core-root")
target_link_options(core_driver_tests PRIVATE -Wl,--gc-sections)
target_link_libraries(core_driver_tests PRIVATE undo_driver)