add_executable(deck_test_upload_tests tests/deck_test_upload_tests.cpp)
target_compile_features(deck_test_upload_tests PRIVATE cxx_std_17)
target_include_directories(deck_test_upload_tests PRIVATE tests client/gframe)
target_link_options(deck_test_upload_tests PRIVATE -static)
configure_undo_host_target(deck_test_upload_tests)
if(UNDO_TEST_RUNTIME_ROOT)
    add_test(NAME deck_test_upload_tests COMMAND deck_test_upload_tests "${UNDO_TEST_RUNTIME_ROOT}")
    set_tests_properties(deck_test_upload_tests PROPERTIES TIMEOUT 90)
endif()
