add_executable(deck_test_query_tests tests/deck_test_query_tests.cpp tests/core_test_globals.cpp)
target_compile_features(deck_test_query_tests PRIVATE cxx_std_17)
target_include_directories(deck_test_query_tests PRIVATE tests client/gframe)
target_link_libraries(deck_test_query_tests PRIVATE undo_driver)
target_link_options(deck_test_query_tests PRIVATE -static -Wl,--gc-sections)
target_compile_definitions(deck_test_query_tests PRIVATE UNDO_POOL_FIXTURE="${CMAKE_CURRENT_SOURCE_DIR}/out/tests/results/pool-query")
set(UNDO_POOL_RUNTIME_ROOT "" CACHE PATH "Read-only resources for actual c62962630 query gate")
if(UNDO_POOL_RUNTIME_ROOT)
 add_test(NAME deck_test_query_tests COMMAND deck_test_query_tests "${UNDO_POOL_RUNTIME_ROOT}")
 set_tests_properties(deck_test_query_tests PROPERTIES TIMEOUT 180)
endif()
add_executable(deck_test_introduction_tests tests/deck_test_introduction_tests.cpp tests/core_test_globals.cpp)
target_compile_features(deck_test_introduction_tests PRIVATE cxx_std_17)
target_include_directories(deck_test_introduction_tests PRIVATE tests client/gframe)
target_link_libraries(deck_test_introduction_tests PRIVATE undo_driver)
target_link_options(deck_test_introduction_tests PRIVATE -static -Wl,--gc-sections)
target_compile_definitions(deck_test_introduction_tests PRIVATE UNDO_INTRODUCTION_FIXTURE="${CMAKE_CURRENT_SOURCE_DIR}/out/tests/results/pool-introduction")
if(UNDO_POOL_RUNTIME_ROOT)
 add_test(NAME deck_test_introduction_tests COMMAND deck_test_introduction_tests "${UNDO_POOL_RUNTIME_ROOT}")
 set_tests_properties(deck_test_introduction_tests PROPERTIES TIMEOUT 240)
endif()
add_executable(query_identity_tests tests/query_identity_tests.cpp tests/core_test_globals.cpp)
target_compile_features(query_identity_tests PRIVATE cxx_std_17)
target_include_directories(query_identity_tests PRIVATE tests client/gframe)
target_link_libraries(query_identity_tests PRIVATE undo_driver)
target_link_options(query_identity_tests PRIVATE -static -Wl,--gc-sections)
target_compile_definitions(query_identity_tests PRIVATE
 UNDO_IDENTITY_FIXTURE="${CMAKE_CURRENT_SOURCE_DIR}/out/tests/results/query-identity"
 UNDO_IDENTITY_SCRIPT="${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/query-identity/c900000120.lua")
if(UNDO_POOL_RUNTIME_ROOT)
 add_test(NAME query_identity_tests COMMAND query_identity_tests "${UNDO_POOL_RUNTIME_ROOT}")
 set_tests_properties(query_identity_tests PROPERTIES TIMEOUT 240)
endif()
add_executable(fusion_gold_query_tests tests/fusion_gold_query_tests.cpp tests/core_test_globals.cpp)
target_compile_features(fusion_gold_query_tests PRIVATE cxx_std_17)
target_include_directories(fusion_gold_query_tests PRIVATE tests client/gframe)
target_link_libraries(fusion_gold_query_tests PRIVATE undo_driver)
target_link_options(fusion_gold_query_tests PRIVATE -static -Wl,--gc-sections)
if(UNDO_POOL_RUNTIME_ROOT)
 add_test(NAME fusion_gold_query_tests COMMAND fusion_gold_query_tests "${UNDO_POOL_RUNTIME_ROOT}")
 set_tests_properties(fusion_gold_query_tests PROPERTIES TIMEOUT 180)
endif()
