add_executable(hidden_source_tests tests/hidden_source_tests.cpp)
target_compile_features(hidden_source_tests PRIVATE cxx_std_17)
target_include_directories(hidden_source_tests PRIVATE tests client/gframe)
configure_undo_host_target(hidden_source_tests)
target_link_options(hidden_source_tests PRIVATE -static)
target_compile_definitions(hidden_source_tests PRIVATE UNDO_HIDDEN_FIXTURE="${CMAKE_CURRENT_SOURCE_DIR}/out/tests/results/hidden-source")
if(UNDO_POOL_RUNTIME_ROOT)
 if(UNDO_BOT_TEST_EXE AND UNDO_BOT_TEST_RUNTIME)
  add_test(NAME hidden_source_tests COMMAND hidden_source_tests "${UNDO_POOL_RUNTIME_ROOT}" "${UNDO_BOT_TEST_EXE}" "${UNDO_BOT_TEST_RUNTIME}")
 else()
  add_test(NAME hidden_source_tests COMMAND hidden_source_tests "${UNDO_POOL_RUNTIME_ROOT}")
 endif()
 set_tests_properties(hidden_source_tests PROPERTIES TIMEOUT 240)
endif()
set(UNDO_MANAGED_TEST_EXE "" CACHE FILEPATH "Built managed native-source recipient checks")
if(UNDO_MANAGED_TEST_EXE AND UNDO_POOL_RUNTIME_ROOT AND UNDO_BOT_TEST_EXE AND UNDO_BOT_TEST_RUNTIME)
 set_tests_properties(hidden_source_tests PROPERTIES FIXTURES_SETUP hidden_source_packets)
 add_test(NAME hidden_source_managed_tests COMMAND "${UNDO_MANAGED_TEST_EXE}" --native-fixture "${CMAKE_CURRENT_SOURCE_DIR}/out/tests/results/hidden-source")
 set_tests_properties(hidden_source_managed_tests PROPERTIES TIMEOUT 180 FIXTURES_REQUIRED hidden_source_packets ENVIRONMENT "WIND_BOT_RUNTIME=${UNDO_BOT_TEST_RUNTIME}")
endif()
