add_executable(match_duel_tests tests/match_duel_tests.cpp)
target_compile_features(match_duel_tests PRIVATE cxx_std_17)
target_include_directories(match_duel_tests PRIVATE tests client/gframe)
target_link_options(match_duel_tests PRIVATE -static)
configure_undo_host_target(match_duel_tests)
if(UNDO_TEST_RUNTIME_ROOT)
    foreach(mode series epochs terminal draws bot-match round-failure)
        add_test(NAME match_duel_${mode} COMMAND match_duel_tests "${UNDO_TEST_RUNTIME_ROOT}" "${mode}")
        set_tests_properties(match_duel_${mode} PROPERTIES TIMEOUT 90)
    endforeach()
endif()
