add_executable(native_duel_flow_tests tests/native_duel_flow_tests.cpp)
target_compile_features(native_duel_flow_tests PRIVATE cxx_std_17)
target_include_directories(native_duel_flow_tests PRIVATE tests client/gframe)
target_link_options(native_duel_flow_tests PRIVATE -static)
configure_undo_host_target(native_duel_flow_tests)
if(UNDO_TEST_RUNTIME_ROOT)
    add_test(NAME native_duel_flow_tests COMMAND native_duel_flow_tests "${UNDO_TEST_RUNTIME_ROOT}")
    set_tests_properties(native_duel_flow_tests PROPERTIES TIMEOUT 90)
endif()
