if(WIN32)
    add_undo_test(runtime_paths_tests tests/runtime_paths_tests.cpp)
    target_sources(runtime_paths_tests PRIVATE client/gframe/undo/runtime_paths.cpp)
    target_link_libraries(runtime_paths_tests PRIVATE shell32)
    add_undo_test(config_store_tests tests/config_store_tests.cpp)
    target_sources(config_store_tests PRIVATE client/gframe/undo/config_store.cpp client/gframe/undo/runtime_paths.cpp)
    target_link_libraries(config_store_tests PRIVATE bcrypt shell32)
    if(MINGW)
        target_link_options(config_store_tests PRIVATE -municode)
    endif()
endif()
