add_library(undo_single STATIC client/gframe/undo/single_undo.cpp client/gframe/undo/duel_history.cpp client/gframe/undo/protocol.cpp)
target_link_libraries(undo_single PUBLIC undo_rebuilder)
add_executable(single_undo_tests tests/single_undo_tests.cpp tests/core_test_globals.cpp)
target_link_libraries(single_undo_tests PRIVATE undo_single)
target_include_directories(single_undo_tests PRIVATE tests client/gframe)
target_link_options(single_undo_tests PRIVATE -static -Wl,--gc-sections)
if(UNDO_TEST_RUNTIME_ROOT)
 add_test(NAME single_undo_tests COMMAND single_undo_tests "${UNDO_TEST_RUNTIME_ROOT}")
endif()
