add_executable(undo_bot_host_tests tests/undo_bot_host_tests.cpp)
target_compile_features(undo_bot_host_tests PRIVATE cxx_std_17)
target_include_directories(undo_bot_host_tests PRIVATE tests client/gframe)
target_link_options(undo_bot_host_tests PRIVATE -static)
configure_undo_host_target(undo_bot_host_tests)
target_link_libraries(undo_bot_host_tests PRIVATE advapi32 shell32)
if(UNDO_BOT_TEST_EXE AND UNDO_TEST_RUNTIME_ROOT)
    add_test(NAME undo_bot_host_tests COMMAND undo_bot_host_tests "${UNDO_BOT_TEST_EXE}" "${UNDO_TEST_RUNTIME_ROOT}")
    set_tests_properties(undo_bot_host_tests PROPERTIES TIMEOUT 180)
endif()
