add_executable(undo_tcp_tests tests/undo_tcp_tests.cpp)
target_compile_features(undo_tcp_tests PRIVATE cxx_std_17)
target_include_directories(undo_tcp_tests PRIVATE tests client/gframe)
target_link_options(undo_tcp_tests PRIVATE -static)
configure_undo_host_target(undo_tcp_tests)
if(UNDO_TEST_RUNTIME_ROOT)
    add_test(NAME undo_tcp_tests COMMAND undo_tcp_tests "${UNDO_TEST_RUNTIME_ROOT}")
    set_tests_properties(undo_tcp_tests PROPERTIES TIMEOUT 90)
    add_test(NAME undo_tcp_prepare_disconnect COMMAND undo_tcp_tests "${UNDO_TEST_RUNTIME_ROOT}" prepare)
    add_test(NAME undo_tcp_commit_disconnect COMMAND undo_tcp_tests "${UNDO_TEST_RUNTIME_ROOT}" commit)
    add_test(NAME undo_tcp_lobby_replacement COMMAND undo_tcp_tests "${UNDO_TEST_RUNTIME_ROOT}" replacement)
    set_tests_properties(undo_tcp_prepare_disconnect undo_tcp_commit_disconnect undo_tcp_lobby_replacement PROPERTIES TIMEOUT 90)
    add_test(NAME undo_tcp_policy_paused COMMAND undo_tcp_tests "${UNDO_TEST_RUNTIME_ROOT}" policy)
    add_test(NAME undo_tcp_busy_request COMMAND undo_tcp_tests "${UNDO_TEST_RUNTIME_ROOT}" busy)
    add_test(NAME undo_tcp_post_duel_replay COMMAND undo_tcp_tests "${UNDO_TEST_RUNTIME_ROOT}" replay)
    set_tests_properties(undo_tcp_policy_paused undo_tcp_busy_request undo_tcp_post_duel_replay PROPERTIES TIMEOUT 90)
endif()
