add_executable(undo_duel_tests tests/undo_duel_tests.cpp)
target_compile_features(undo_duel_tests PRIVATE cxx_std_17)
target_include_directories(undo_duel_tests PRIVATE tests client/gframe)
target_link_options(undo_duel_tests PRIVATE -static)
configure_undo_host_target(undo_duel_tests)
if(UNDO_TEST_RUNTIME_ROOT)
    add_test(NAME undo_duel_tests COMMAND undo_duel_tests "${UNDO_TEST_RUNTIME_ROOT}")
    set_tests_properties(undo_duel_tests PROPERTIES TIMEOUT 90)
endif()
