add_executable(undo_host_privacy_tests tests/undo_host_privacy_tests.cpp)
target_compile_features(undo_host_privacy_tests PRIVATE cxx_std_17)
target_include_directories(undo_host_privacy_tests PRIVATE tests client/gframe)
target_link_options(undo_host_privacy_tests PRIVATE -static)
configure_undo_host_target(undo_host_privacy_tests)
if(UNDO_TEST_RUNTIME_ROOT)
    add_test(NAME undo_host_privacy_tests COMMAND undo_host_privacy_tests "${UNDO_TEST_RUNTIME_ROOT}")
    set_tests_properties(undo_host_privacy_tests PROPERTIES TIMEOUT 90)
endif()